DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS events;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  urole TEXT NOT NULL CHECK,
  uname TEXT UNIQUE NOT NULL,
  pass TEXT NOT NULL
);

CREATE TABLE events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  locat TEXT NOT NULL,
)
